from __future__ import annotations

import fnmatch
from pathlib import PurePosixPath

from pydantic import Field

from apoapsis.repository.fingerprint import (
    is_safe_relative_path,
    normalize_relative_path,
)
from apoapsis.specification.schema import StrictModel


# Glob patterns, matched against a POSIX-normalized repository-relative path,
# that identify files a *tool run* produces rather than files a model authored.
#
# This exists because a live Laguna task (TASK-EF33C00E5BD4, 2026-07-26)
# reported `__pycache__/calc.cpython-314.pyc` and
# `tests/__pycache__/test_calc.cpython-314.pyc` as changed files alongside the
# one source file the model actually edited. The bytecode was written by the
# harness's own verification run, inside a scratch repository whose
# `.gitignore` did not exclude it. A reviewer reading that list cannot tell
# what the model did.
#
# Deliberately *not* driven by `.gitignore`: reviewer-facing output must be
# correct against repositories the harness did not initialize, and existing
# projects cannot be assumed to carry the ignore rules `apoapsis init` writes.
GENERATED_BYPRODUCT_PATTERNS: tuple[str, ...] = (
    "__pycache__/**",
    "**/__pycache__/**",
    "**/*.pyc",
    "**/*.pyo",
    "**/*.pyd",
    ".pytest_cache/**",
    "**/.pytest_cache/**",
    ".mypy_cache/**",
    "**/.mypy_cache/**",
    ".ruff_cache/**",
    "**/.ruff_cache/**",
    ".tox/**",
    ".nox/**",
    "htmlcov/**",
    "**/.coverage",
    "**/.coverage.*",
    "coverage.xml",
    ".hypothesis/**",
    "**/*.egg-info/**",
    "**/node_modules/**",
    ".gradle/**",
    "target/debug/**",
    "target/release/**",
)


def is_generated_byproduct_path(path: str) -> bool:
    """True when `path` names a build/test byproduct rather than authored work.

    Pure name-based classification over a normalized relative path. It makes
    no filesystem or Git call, so it is deterministic and cheap enough to run
    on every changed-path listing.
    """

    normalized = normalize_relative_path(path)
    if not normalized:
        return False
    parts = PurePosixPath(normalized).parts
    if "__pycache__" in parts:
        return True
    return any(
        fnmatch.fnmatch(normalized, pattern)
        for pattern in GENERATED_BYPRODUCT_PATTERNS
    )


class ChangedPathClassification(StrictModel):
    """A changed-path listing split into the three questions a reviewer and
    the controller each need answered separately (see ADR 0063).

    `reviewable` is the model-authored change surface. `generated_byproducts`
    is retained rather than discarded: audit evidence must still show that
    running verification mutated the worktree, even though that clutter must
    never be presented as task output.
    """

    reviewable: list[str] = Field(default_factory=list)
    generated_byproducts: list[str] = Field(default_factory=list)
    rejected: list[str] = Field(default_factory=list)


def classify_changed_paths(
    paths: list[str] | set[str] | tuple[str, ...],
    *,
    tracked_paths: set[str] | frozenset[str] | None = None,
) -> ChangedPathClassification:
    """Split changed paths into reviewable work, generated byproducts, and
    paths rejected outright by the shared path-safety policy.

    A path already tracked in Git is always reviewable, even when its name
    matches a generated pattern. Somebody deliberately committed it, so a
    legitimate modification to it is the model's work and must not be hidden
    from review just because it looks like clutter.
    """

    tracked = {normalize_relative_path(item) for item in (tracked_paths or set())}
    reviewable: set[str] = set()
    generated: set[str] = set()
    rejected: set[str] = set()
    for raw in paths:
        normalized = normalize_relative_path(raw)
        if not is_safe_relative_path(normalized):
            rejected.add(normalized)
            continue
        if normalized not in tracked and is_generated_byproduct_path(normalized):
            generated.add(normalized)
            continue
        reviewable.add(normalized)
    return ChangedPathClassification(
        reviewable=sorted(reviewable),
        generated_byproducts=sorted(generated),
        rejected=sorted(rejected),
    )


__all__ = [
    "GENERATED_BYPRODUCT_PATTERNS",
    "ChangedPathClassification",
    "classify_changed_paths",
    "is_generated_byproduct_path",
]
